# Generated by Django 4.2.8 on 2023-12-11 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0003_song_alter_artist_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tunaapi.artist'),
        ),
    ]
